import type { Seller, Category, Product, Coupon } from "../types/marketplace";

const ago    = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const future = (d: number) => new Date(Date.now() + d * 86_400_000).toISOString();
const rand   = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
let vseq = 0;
const vid = () => `v-${(++vseq).toString(36)}`;

// ─── Categories ─────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  { id:"cat-01", name:"Electronics",       slug:"electronics",     icon:"💻", parentId:null, productCount:0, featured:true  },
  { id:"cat-02", name:"Fashion",           slug:"fashion",         icon:"👗", parentId:null, productCount:0, featured:true  },
  { id:"cat-03", name:"Home & Garden",     slug:"home-garden",     icon:"🏠", parentId:null, productCount:0, featured:true  },
  { id:"cat-04", name:"Health & Beauty",   slug:"health-beauty",   icon:"💄", parentId:null, productCount:0, featured:true  },
  { id:"cat-05", name:"Sports",            slug:"sports",          icon:"⚽", parentId:null, productCount:0, featured:true  },
  { id:"cat-06", name:"Books & Media",     slug:"books-media",     icon:"📚", parentId:null, productCount:0, featured:false },
];

// ─── Sellers ────────────────────────────────────────────────────────────────
export const SELLERS: Seller[] = [
  { id:"sel-01", userId:"", storeName:"TechZone",    storeSlug:"techzone",    description:"Zambia's leading electronics retailer",   logoUrl:null, bannerUrl:null, email:"store@techzone.example",  phone:"+260970000001", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0001", totalProducts:0, totalSales:842, totalRevenue:1_480_000, avgRating:4.7, reviewCount:520, joinedAt:ago(43800), commissionPct:8 },
  { id:"sel-02", userId:"", storeName:"Fashion Hub",  storeSlug:"fashion-hub", description:"Trendy clothing for the modern shopper",  logoUrl:null, bannerUrl:null, email:"store@fashionhub.example", phone:"+260970000002", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0002", totalProducts:0, totalSales:434, totalRevenue:280_000,  avgRating:4.5, reviewCount:310, joinedAt:ago(30000), commissionPct:10 },
  { id:"sel-03", userId:"", storeName:"HomeStyle",    storeSlug:"homestyle",   description:"Quality furniture and home décor",        logoUrl:null, bannerUrl:null, email:"store@homestyle.example",  phone:"+260970000003", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0003", totalProducts:0, totalSales:221, totalRevenue:520_000,  avgRating:4.6, reviewCount:180, joinedAt:ago(25000), commissionPct:9 },
  { id:"sel-04", userId:"", storeName:"SportsPro",    storeSlug:"sportspro",   description:"Professional sporting goods & fitness",   logoUrl:null, bannerUrl:null, email:"store@sportspro.example",  phone:"+260970000004", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0004", totalProducts:0, totalSales:283, totalRevenue:140_000,  avgRating:4.4, reviewCount:140, joinedAt:ago(20000), commissionPct:8 },
  { id:"sel-05", userId:"", storeName:"BeautyBar",    storeSlug:"beautybar",   description:"Premium skincare & cosmetics",            logoUrl:null, bannerUrl:null, email:"store@beautybar.example",  phone:"+260970000005", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0005", totalProducts:0, totalSales:603, totalRevenue:110_000,  avgRating:4.8, reviewCount:420, joinedAt:ago(18000), commissionPct:12 },
  { id:"sel-06", userId:"", storeName:"BookWorld",    storeSlug:"bookworld",   description:"Books, stationery and media",             logoUrl:null, bannerUrl:null, email:"store@bookworld.example",  phone:"+260970000006", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0006", totalProducts:0, totalSales:198, totalRevenue:35_000,   avgRating:4.3, reviewCount:90,  joinedAt:ago(15000), commissionPct:6 },
];

// ─── Products ───────────────────────────────────────────────────────────────
const SEED: Omit<Product, "id" | "slug" | "createdAt" | "updatedAt">[] = [
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Galaxy S25 Ultra", shortDescription:"6.8\" AMOLED, 200MP camera, S Pen included", description:"A flagship smartphone with a large AMOLED display, 200MP camera system, and included S Pen stylus.", price:22999, compareAtPrice:25999, currency:"ZMW", images:["#1a1a2e","#16213e"], emoji:"📱", status:"active", stock:48, sku:"GX-S25U", brand:"Galaxy", tags:["flagship","android","5g"], attributes:{Storage:"512GB",RAM:"12GB",Color:"Black"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:28,sku:"GX-S25U-BLK"},{id:vid(),type:"color",value:"Titanium",additionalPrice:0,stock:20,sku:"GX-S25U-TIT"}], avgRating:4.8, reviewCount:342, totalSold:184, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Pro Laptop 14\"", shortDescription:"14-core GPU, 16GB RAM, 512GB SSD", description:"A powerful, lightweight laptop for professional work, with all-day battery life.", price:26999, compareAtPrice:29999, currency:"ZMW", images:["#2d3748","#1a202c"], emoji:"💻", status:"active", stock:22, sku:"PL-14", brand:"ProBook", tags:["laptop","professional"], attributes:{RAM:"16GB",Storage:"512GB",Color:"Space Grey"}, variants:[{id:vid(),type:"style",value:"16GB / 512GB",additionalPrice:0,stock:22,sku:"PL14-16-512"}], avgRating:4.9, reviewCount:218, totalSold:96, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Wireless Headphones", shortDescription:"Noise cancellation, 40h battery", description:"Immersive sound with industry-leading active noise cancellation and a 40-hour battery life.", price:2999, compareAtPrice:3799, currency:"ZMW", images:["#1a1a2e","#2d3748"], emoji:"🎧", status:"active", stock:85, sku:"WH-1000", brand:"AudioMax", tags:["audio","wireless","anc"], attributes:{Color:"Black",BatteryLife:"40 Hours"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:50,sku:"WH-BLK"},{id:vid(),type:"color",value:"Silver",additionalPrice:0,stock:35,sku:"WH-SLV"}], avgRating:4.7, reviewCount:520, totalSold:340, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"55\" 4K Smart TV", shortDescription:"HDR, 120Hz, built-in streaming apps", description:"Transform your living room with vivid 4K HDR picture and smooth 120Hz motion.", price:8999, compareAtPrice:10999, currency:"ZMW", images:["#0a0a0a","#1a1a2e"], emoji:"📺", status:"active", stock:15, sku:"TV-55-4K", brand:"Vista", tags:["tv","4k","smart"], attributes:{Size:"55 inch",Resolution:"4K"}, variants:[{id:vid(),type:"style",value:"55 inch",additionalPrice:0,stock:15,sku:"TV55-55"}], avgRating:4.6, reviewCount:89, totalSold:52, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Fitness Smartwatch", shortDescription:"Heart rate, GPS, 18h battery", description:"Track your health and fitness with an always-on display and comprehensive sensor suite.", price:3999, compareAtPrice:4999, currency:"ZMW", images:["#1c1c1e","#2d3748"], emoji:"⌚", status:"active", stock:63, sku:"SW-10", brand:"PulseFit", tags:["smartwatch","fitness","health"], attributes:{Case:"Aluminium",Band:"Sport Loop"}, variants:[{id:vid(),type:"size",value:"42mm",additionalPrice:0,stock:40,sku:"SW10-42"},{id:vid(),type:"size",value:"46mm",additionalPrice:200,stock:23,sku:"SW10-46"}], avgRating:4.8, reviewCount:175, totalSold:88, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Air Max Sneakers", shortDescription:"Lifestyle sneaker, breathable mesh upper", description:"All-day comfort with a large visible air unit and breathable mesh construction.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#E8E8E8","#FFFFFF"], emoji:"👟", status:"active", stock:120, sku:"AM-270", brand:"Stride", tags:["shoes","sneakers","sport"], attributes:{Material:"Mesh + Leather"}, variants:[{id:vid(),type:"size",value:"7",additionalPrice:0,stock:20,sku:"AM270-7"},{id:vid(),type:"size",value:"8",additionalPrice:0,stock:30,sku:"AM270-8"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:35,sku:"AM270-9"},{id:vid(),type:"size",value:"10",additionalPrice:0,stock:25,sku:"AM270-10"}], avgRating:4.6, reviewCount:890, totalSold:620, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Classic Straight Jeans", shortDescription:"Straight fit, button fly, 100% cotton denim", description:"A timeless straight-fit jean in durable, comfortable 100% cotton denim.", price:499, compareAtPrice:null, currency:"ZMW", images:["#1a237e","#283593"], emoji:"👖", status:"active", stock:200, sku:"CJ-501", brand:"Denimco", tags:["jeans","denim","classic"], attributes:{Fit:"Straight",Material:"100% Cotton"}, variants:[{id:vid(),type:"size",value:"30x30",additionalPrice:0,stock:40,sku:"CJ-3030"},{id:vid(),type:"size",value:"32x32",additionalPrice:0,stock:60,sku:"CJ-3232"},{id:vid(),type:"size",value:"34x32",additionalPrice:0,stock:60,sku:"CJ-3432"}], avgRating:4.5, reviewCount:412, totalSold:380, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Classic Aviator Sunglasses", shortDescription:"Polarized lenses, gold metal frame, UV400", description:"Timeless aviator styling with polarized lenses and full UV400 protection.", price:699, compareAtPrice:899, currency:"ZMW", images:["#D4AF37","#B8860B"], emoji:"🕶️", status:"active", stock:75, sku:"AV-3025", brand:"Skyline", tags:["sunglasses","fashion","uv"], attributes:{Frame:"Gold Metal",Lens:"Polarized"}, variants:[], avgRating:4.7, reviewCount:234, totalSold:142, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Stand Mixer", shortDescription:"5.7L bowl, 10 speeds, classic design", description:"A versatile kitchen companion for baking, mixing, and more.", price:3499, compareAtPrice:3999, currency:"ZMW", images:["#E53935","#B71C1C"], emoji:"🍳", status:"active", stock:28, sku:"SM-175", brand:"Homeware", tags:["kitchen","baking","mixer"], attributes:{Capacity:"5.7L",Color:"Red"}, variants:[{id:vid(),type:"color",value:"Red",additionalPrice:0,stock:15,sku:"SM-RED"},{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:13,sku:"SM-BLK"}], avgRating:4.9, reviewCount:182, totalSold:94, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Cordless Vacuum", shortDescription:"60min runtime, HEPA filtration", description:"Powerful, lightweight cordless cleaning that adapts to different floor types.", price:4999, compareAtPrice:5999, currency:"ZMW", images:["#F9A825","#F57F17"], emoji:"🧹", status:"active", stock:35, sku:"CV-15", brand:"CleanPro", tags:["vacuum","cordless","cleaning"], attributes:{BatteryLife:"60 min",Weight:"3.1kg"}, variants:[], avgRating:4.8, reviewCount:267, totalSold:156, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Skincare Essentials Bundle", shortDescription:"Cleanser, serum, moisturizer, SPF", description:"A complete daily skincare routine in one bundle, suitable for all skin types.", price:349, compareAtPrice:449, currency:"ZMW", images:["#FAFAFA","#F5F5F5"], emoji:"💆", status:"active", stock:340, sku:"SK-BND-01", brand:"PureGlow", tags:["skincare","routine"], attributes:{SkinType:"All Types",Items:"4"}, variants:[], avgRating:4.7, reviewCount:892, totalSold:740, isFeatured:true, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Electric Toothbrush", shortDescription:"7 brushing modes, pressure sensor", description:"Gentle, effective cleaning with smart pressure sensing and multiple modes.", price:899, compareAtPrice:1199, currency:"ZMW", images:["#1565C0","#0D47A1"], emoji:"🪥", status:"active", stock:62, sku:"ET-9", brand:"BrightSmile", tags:["dental","electric","health"], attributes:{Modes:"7",BatteryLife:"14 days"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:35,sku:"ET9-BLK"},{id:vid(),type:"color",value:"White",additionalPrice:0,stock:27,sku:"ET9-WHT"}], avgRating:4.6, reviewCount:194, totalSold:112, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Multi-Sport GPS Watch", shortDescription:"GPS tracking, AMOLED display, 29-day battery", description:"The ultimate companion for runners, cyclists, and swimmers alike.", price:5999, compareAtPrice:6999, currency:"ZMW", images:["#1a1a2e","#2d3748"], emoji:"🏃", status:"active", stock:18, sku:"GPS-8", brand:"TrailTrack", tags:["gps","sport","fitness"], attributes:{Display:"AMOLED",WaterRating:"100m"}, variants:[{id:vid(),type:"size",value:"47mm",additionalPrice:0,stock:10,sku:"GPS8-47"},{id:vid(),type:"size",value:"51mm",additionalPrice:300,stock:8,sku:"GPS8-51"}], avgRating:4.8, reviewCount:128, totalSold:74, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Running Shoes", shortDescription:"Energy-returning midsole, breathable knit upper", description:"Engineered for distance running with exceptional cushioning and energy return.", price:1099, compareAtPrice:1299, currency:"ZMW", images:["#FFFFFF","#EEEEEE"], emoji:"👟", status:"active", stock:95, sku:"RS-24", brand:"Stride", tags:["running","shoes","performance"], attributes:{Drop:"10mm",Weight:"310g"}, variants:[{id:vid(),type:"size",value:"8",additionalPrice:0,stock:20,sku:"RS24-8"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:30,sku:"RS24-9"},{id:vid(),type:"size",value:"10",additionalPrice:0,stock:30,sku:"RS24-10"}], avgRating:4.6, reviewCount:340, totalSold:245, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Atomic Habits", shortDescription:"Proven framework for building good habits", description:"A bestselling guide to making small changes that deliver remarkable results.", price:149, compareAtPrice:179, currency:"ZMW", images:["#1A237E","#283593"], emoji:"📖", status:"active", stock:500, sku:"BK-AH", brand:"BookWorld Press", tags:["self-help","habits","bestseller"], attributes:{Format:"Paperback",Pages:"320"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:400,sku:"AH-PB"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:60,stock:100,sku:"AH-HC"}], avgRating:4.9, reviewCount:1204, totalSold:892, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
];

export const PRODUCTS: Product[] = SEED.map((p, i) => ({
  ...p,
  id: `prod-${String(i + 1).padStart(3, "0")}`,
  slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  createdAt: ago(rand(720, 43800)),
  updatedAt: ago(rand(0, 720)),
}));

CATEGORIES.forEach(c => { c.productCount = PRODUCTS.filter(p => p.categoryId === c.id).length; });

// ─── Coupons ────────────────────────────────────────────────────────────────
export const COUPONS: Coupon[] = [
  { id:"cpn-01", code:"WELCOME10", type:"percentage",    value:10, minOrderAmount:200, maxDiscountAmount:100, usageLimit:null, usageCount:0, validFrom:ago(43800), validTo:future(365), active:true, sellerId:null },
  { id:"cpn-02", code:"SAVE50",    type:"fixed_amount",  value:50, minOrderAmount:400, maxDiscountAmount:null, usageLimit:5000, usageCount:0, validFrom:ago(4380), validTo:future(30), active:true, sellerId:null },
  { id:"cpn-03", code:"FREESHIP",  type:"free_shipping", value:0,  minOrderAmount:100, maxDiscountAmount:null, usageLimit:null, usageCount:0, validFrom:ago(8760), validTo:future(90), active:true, sellerId:null },
];
