import { randomUUID } from "crypto";
import type { Seller, Category, Product, Coupon } from "../types/marketplace";

const ago    = (m: number) => new Date(Date.now() - m * 60_000).toISOString();
const future = (d: number) => new Date(Date.now() + d * 86_400_000).toISOString();
const rand   = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
let vseq = 0;
const vid = () => `v-${(++vseq).toString(36)}`;

// ─── Categories ─────────────────────────────────────────────────────────────
export const CATEGORIES: Category[] = [
  { id:"cat-01", name:"Electronics",       slug:"electronics",     icon:"💻", parentId:null, productCount:0, featured:true  },
  { id:"cat-02", name:"Fashion",           slug:"fashion",         icon:"👗", parentId:null, productCount:0, featured:true  },
  { id:"cat-03", name:"Home & Garden",     slug:"home-garden",     icon:"🏠", parentId:null, productCount:0, featured:true  },
  { id:"cat-04", name:"Health & Beauty",   slug:"health-beauty",   icon:"💄", parentId:null, productCount:0, featured:true  },
  { id:"cat-05", name:"Sports",            slug:"sports",          icon:"⚽", parentId:null, productCount:0, featured:true  },
  { id:"cat-06", name:"Books & Media",     slug:"books-media",     icon:"📚", parentId:null, productCount:0, featured:false },
];

// ─── Sellers ────────────────────────────────────────────────────────────────
export const SELLERS: Seller[] = [
  { id:"sel-01", userId:"", storeName:"TechZone",    storeSlug:"techzone",    description:"Zambia's leading electronics retailer",   logoUrl:null, bannerUrl:null, email:"store@techzone.example",  phone:"+260970000001", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0001", totalProducts:0, totalSales:842, totalRevenue:1_480_000, avgRating:4.7, reviewCount:520, joinedAt:ago(43800), commissionPct:8 },
  { id:"sel-02", userId:"", storeName:"Fashion Hub",  storeSlug:"fashion-hub", description:"Trendy clothing for the modern shopper",  logoUrl:null, bannerUrl:null, email:"store@fashionhub.example", phone:"+260970000002", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0002", totalProducts:0, totalSales:434, totalRevenue:280_000,  avgRating:4.5, reviewCount:310, joinedAt:ago(30000), commissionPct:10 },
  { id:"sel-03", userId:"", storeName:"HomeStyle",    storeSlug:"homestyle",   description:"Quality furniture and home décor",        logoUrl:null, bannerUrl:null, email:"store@homestyle.example",  phone:"+260970000003", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0003", totalProducts:0, totalSales:221, totalRevenue:520_000,  avgRating:4.6, reviewCount:180, joinedAt:ago(25000), commissionPct:9 },
  { id:"sel-04", userId:"", storeName:"SportsPro",    storeSlug:"sportspro",   description:"Professional sporting goods & fitness",   logoUrl:null, bannerUrl:null, email:"store@sportspro.example",  phone:"+260970000004", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0004", totalProducts:0, totalSales:283, totalRevenue:140_000,  avgRating:4.4, reviewCount:140, joinedAt:ago(20000), commissionPct:8 },
  { id:"sel-05", userId:"", storeName:"BeautyBar",    storeSlug:"beautybar",   description:"Premium skincare & cosmetics",            logoUrl:null, bannerUrl:null, email:"store@beautybar.example",  phone:"+260970000005", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0005", totalProducts:0, totalSales:603, totalRevenue:110_000,  avgRating:4.8, reviewCount:420, joinedAt:ago(18000), commissionPct:12 },
  { id:"sel-06", userId:"", storeName:"BookWorld",    storeSlug:"bookworld",   description:"Books, stationery and media",             logoUrl:null, bannerUrl:null, email:"store@bookworld.example",  phone:"+260970000006", country:"ZM", status:"active", kycVerified:true, taxId:"TZ-0006", totalProducts:0, totalSales:198, totalRevenue:35_000,   avgRating:4.3, reviewCount:90,  joinedAt:ago(15000), commissionPct:6 },
];

// ─── Products ───────────────────────────────────────────────────────────────
const SEED: Omit<Product, "id" | "slug" | "createdAt" | "updatedAt">[] = [
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Galaxy S25 Ultra", shortDescription:"6.8\" AMOLED, 200MP camera, S Pen included", description:"A flagship smartphone with a large AMOLED display, 200MP camera system, and included S Pen stylus.", price:22999, compareAtPrice:25999, currency:"ZMW", images:["#1a1a2e","#16213e"], emoji:"📱", status:"active", stock:48, sku:"GX-S25U", brand:"Galaxy", tags:["flagship","android","5g"], attributes:{Storage:"512GB",RAM:"12GB",Color:"Black"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:28,sku:"GX-S25U-BLK"},{id:vid(),type:"color",value:"Titanium",additionalPrice:0,stock:20,sku:"GX-S25U-TIT"}], avgRating:4.8, reviewCount:342, totalSold:184, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Pro Laptop 14\"", shortDescription:"14-core GPU, 16GB RAM, 512GB SSD", description:"A powerful, lightweight laptop for professional work, with all-day battery life.", price:26999, compareAtPrice:29999, currency:"ZMW", images:["#2d3748","#1a202c"], emoji:"💻", status:"active", stock:22, sku:"PL-14", brand:"ProBook", tags:["laptop","professional"], attributes:{RAM:"16GB",Storage:"512GB",Color:"Space Grey"}, variants:[{id:vid(),type:"style",value:"16GB / 512GB",additionalPrice:0,stock:22,sku:"PL14-16-512"}], avgRating:4.9, reviewCount:218, totalSold:96, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Wireless Headphones", shortDescription:"Noise cancellation, 40h battery", description:"Immersive sound with industry-leading active noise cancellation and a 40-hour battery life.", price:2999, compareAtPrice:3799, currency:"ZMW", images:["#1a1a2e","#2d3748"], emoji:"🎧", status:"active", stock:85, sku:"WH-1000", brand:"AudioMax", tags:["audio","wireless","anc"], attributes:{Color:"Black",BatteryLife:"40 Hours"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:50,sku:"WH-BLK"},{id:vid(),type:"color",value:"Silver",additionalPrice:0,stock:35,sku:"WH-SLV"}], avgRating:4.7, reviewCount:520, totalSold:340, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"55\" 4K Smart TV", shortDescription:"HDR, 120Hz, built-in streaming apps", description:"Transform your living room with vivid 4K HDR picture and smooth 120Hz motion.", price:8999, compareAtPrice:10999, currency:"ZMW", images:["#0a0a0a","#1a1a2e"], emoji:"📺", status:"active", stock:15, sku:"TV-55-4K", brand:"Vista", tags:["tv","4k","smart"], attributes:{Size:"55 inch",Resolution:"4K"}, variants:[{id:vid(),type:"style",value:"55 inch",additionalPrice:0,stock:15,sku:"TV55-55"}], avgRating:4.6, reviewCount:89, totalSold:52, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Fitness Smartwatch", shortDescription:"Heart rate, GPS, 18h battery", description:"Track your health and fitness with an always-on display and comprehensive sensor suite.", price:3999, compareAtPrice:4999, currency:"ZMW", images:["#1c1c1e","#2d3748"], emoji:"⌚", status:"active", stock:63, sku:"SW-10", brand:"PulseFit", tags:["smartwatch","fitness","health"], attributes:{Case:"Aluminium",Band:"Sport Loop"}, variants:[{id:vid(),type:"size",value:"42mm",additionalPrice:0,stock:40,sku:"SW10-42"},{id:vid(),type:"size",value:"46mm",additionalPrice:200,stock:23,sku:"SW10-46"}], avgRating:4.8, reviewCount:175, totalSold:88, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Air Max Sneakers", shortDescription:"Lifestyle sneaker, breathable mesh upper", description:"All-day comfort with a large visible air unit and breathable mesh construction.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#E8E8E8","#FFFFFF"], emoji:"👟", status:"active", stock:120, sku:"AM-270", brand:"Stride", tags:["shoes","sneakers","sport"], attributes:{Material:"Mesh + Leather"}, variants:[{id:vid(),type:"size",value:"7",additionalPrice:0,stock:20,sku:"AM270-7"},{id:vid(),type:"size",value:"8",additionalPrice:0,stock:30,sku:"AM270-8"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:35,sku:"AM270-9"},{id:vid(),type:"size",value:"10",additionalPrice:0,stock:25,sku:"AM270-10"}], avgRating:4.6, reviewCount:890, totalSold:620, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Classic Straight Jeans", shortDescription:"Straight fit, button fly, 100% cotton denim", description:"A timeless straight-fit jean in durable, comfortable 100% cotton denim.", price:499, compareAtPrice:null, currency:"ZMW", images:["#1a237e","#283593"], emoji:"👖", status:"active", stock:200, sku:"CJ-501", brand:"Denimco", tags:["jeans","denim","classic"], attributes:{Fit:"Straight",Material:"100% Cotton"}, variants:[{id:vid(),type:"size",value:"30x30",additionalPrice:0,stock:40,sku:"CJ-3030"},{id:vid(),type:"size",value:"32x32",additionalPrice:0,stock:60,sku:"CJ-3232"},{id:vid(),type:"size",value:"34x32",additionalPrice:0,stock:60,sku:"CJ-3432"}], avgRating:4.5, reviewCount:412, totalSold:380, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Classic Aviator Sunglasses", shortDescription:"Polarized lenses, gold metal frame, UV400", description:"Timeless aviator styling with polarized lenses and full UV400 protection.", price:699, compareAtPrice:899, currency:"ZMW", images:["#D4AF37","#B8860B"], emoji:"🕶️", status:"active", stock:75, sku:"AV-3025", brand:"Skyline", tags:["sunglasses","fashion","uv"], attributes:{Frame:"Gold Metal",Lens:"Polarized"}, variants:[], avgRating:4.7, reviewCount:234, totalSold:142, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Stand Mixer", shortDescription:"5.7L bowl, 10 speeds, classic design", description:"A versatile kitchen companion for baking, mixing, and more.", price:3499, compareAtPrice:3999, currency:"ZMW", images:["#E53935","#B71C1C"], emoji:"🍳", status:"active", stock:28, sku:"SM-175", brand:"Homeware", tags:["kitchen","baking","mixer"], attributes:{Capacity:"5.7L",Color:"Red"}, variants:[{id:vid(),type:"color",value:"Red",additionalPrice:0,stock:15,sku:"SM-RED"},{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:13,sku:"SM-BLK"}], avgRating:4.9, reviewCount:182, totalSold:94, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Cordless Vacuum", shortDescription:"60min runtime, HEPA filtration", description:"Powerful, lightweight cordless cleaning that adapts to different floor types.", price:4999, compareAtPrice:5999, currency:"ZMW", images:["#F9A825","#F57F17"], emoji:"🧹", status:"active", stock:35, sku:"CV-15", brand:"CleanPro", tags:["vacuum","cordless","cleaning"], attributes:{BatteryLife:"60 min",Weight:"3.1kg"}, variants:[], avgRating:4.8, reviewCount:267, totalSold:156, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Skincare Essentials Bundle", shortDescription:"Cleanser, serum, moisturizer, SPF", description:"A complete daily skincare routine in one bundle, suitable for all skin types.", price:349, compareAtPrice:449, currency:"ZMW", images:["#FAFAFA","#F5F5F5"], emoji:"💆", status:"active", stock:340, sku:"SK-BND-01", brand:"PureGlow", tags:["skincare","routine"], attributes:{SkinType:"All Types",Items:"4"}, variants:[], avgRating:4.7, reviewCount:892, totalSold:740, isFeatured:true, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Electric Toothbrush", shortDescription:"7 brushing modes, pressure sensor", description:"Gentle, effective cleaning with smart pressure sensing and multiple modes.", price:899, compareAtPrice:1199, currency:"ZMW", images:["#1565C0","#0D47A1"], emoji:"🪥", status:"active", stock:62, sku:"ET-9", brand:"BrightSmile", tags:["dental","electric","health"], attributes:{Modes:"7",BatteryLife:"14 days"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:35,sku:"ET9-BLK"},{id:vid(),type:"color",value:"White",additionalPrice:0,stock:27,sku:"ET9-WHT"}], avgRating:4.6, reviewCount:194, totalSold:112, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Multi-Sport GPS Watch", shortDescription:"GPS tracking, AMOLED display, 29-day battery", description:"The ultimate companion for runners, cyclists, and swimmers alike.", price:5999, compareAtPrice:6999, currency:"ZMW", images:["#1a1a2e","#2d3748"], emoji:"🏃", status:"active", stock:18, sku:"GPS-8", brand:"TrailTrack", tags:["gps","sport","fitness"], attributes:{Display:"AMOLED",WaterRating:"100m"}, variants:[{id:vid(),type:"size",value:"47mm",additionalPrice:0,stock:10,sku:"GPS8-47"},{id:vid(),type:"size",value:"51mm",additionalPrice:300,stock:8,sku:"GPS8-51"}], avgRating:4.8, reviewCount:128, totalSold:74, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Running Shoes", shortDescription:"Energy-returning midsole, breathable knit upper", description:"Engineered for distance running with exceptional cushioning and energy return.", price:1099, compareAtPrice:1299, currency:"ZMW", images:["#FFFFFF","#EEEEEE"], emoji:"👟", status:"active", stock:95, sku:"RS-24", brand:"Stride", tags:["running","shoes","performance"], attributes:{Drop:"10mm",Weight:"310g"}, variants:[{id:vid(),type:"size",value:"8",additionalPrice:0,stock:20,sku:"RS24-8"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:30,sku:"RS24-9"},{id:vid(),type:"size",value:"10",additionalPrice:0,stock:30,sku:"RS24-10"}], avgRating:4.6, reviewCount:340, totalSold:245, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Atomic Habits", shortDescription:"Proven framework for building good habits", description:"A bestselling guide to making small changes that deliver remarkable results.", price:149, compareAtPrice:179, currency:"ZMW", images:["#1A237E","#283593"], emoji:"📖", status:"active", stock:500, sku:"BK-AH", brand:"BookWorld Press", tags:["self-help","habits","bestseller"], attributes:{Format:"Paperback",Pages:"320"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:400,sku:"AH-PB"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:60,stock:100,sku:"AH-HC"}], avgRating:4.9, reviewCount:1204, totalSold:892, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Wireless Earbuds Pro", shortDescription:"ANC, wireless charging case, 30h total battery", description:"Immersive audio with adaptive noise cancellation and a compact charging case.", price:1899, compareAtPrice:2299, currency:"ZMW", images:["#1c1c1e","#2d3748"], emoji:"🎧", status:"active", stock:94, sku:"EB-PRO", brand:"AudioMax", tags:["earbuds","wireless","anc"], attributes:{BatteryLife:"30h"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:25,sku:"EB-PRO-0"},{id:vid(),type:"color",value:"White",additionalPrice:0,stock:19,sku:"EB-PRO-1"}], avgRating:4.5, reviewCount:54, totalSold:57, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"27\" 4K Monitor", shortDescription:"IPS panel, USB-C, 99% sRGB", description:"Crisp, color-accurate display for creative work and everyday productivity.", price:6499, compareAtPrice:7499, currency:"ZMW", images:["#0f172a","#1e293b"], emoji:"🖥️", status:"active", stock:28, sku:"MON-27", brand:"Vista", tags:["monitor","4k","display"], attributes:{Size:"27 inch"}, variants:[], avgRating:4.2, reviewCount:289, totalSold:129, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Mechanical Keyboard", shortDescription:"Hot-swappable switches, RGB backlight", description:"A tactile, customizable keyboard built for long typing sessions and gaming alike.", price:1299, compareAtPrice:1599, currency:"ZMW", images:["#18181b","#27272a"], emoji:"⌨️", status:"active", stock:100, sku:"KB-MX", brand:"ProBook", tags:["keyboard","mechanical","gaming"], attributes:{Switches:"Hot-swappable"}, variants:[{id:vid(),type:"style",value:"Blue switch",additionalPrice:0,stock:22,sku:"KB-MX-0"},{id:vid(),type:"style",value:"Red switch",additionalPrice:0,stock:17,sku:"KB-MX-1"}], avgRating:4.6, reviewCount:60, totalSold:309, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Wireless Mouse", shortDescription:"2.4GHz + Bluetooth, 6-month battery", description:"Precise, silent-click tracking that switches seamlessly between devices.", price:449, compareAtPrice:549, currency:"ZMW", images:["#27272a","#3f3f46"], emoji:"🖱️", status:"active", stock:48, sku:"MS-21", brand:"ProBook", tags:["mouse","wireless"], attributes:{Connection:"2.4GHz + BT"}, variants:[], avgRating:4.6, reviewCount:61, totalSold:315, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Portable SSD 1TB", shortDescription:"USB-C, 1050MB/s read speed", description:"Fast, pocket-sized storage for backups, footage, and everything in between.", price:1699, compareAtPrice:1999, currency:"ZMW", images:["#0a0a0a","#1a1a2e"], emoji:"💾", status:"active", stock:35, sku:"SSD-1TB", brand:"TechZone", tags:["storage","ssd","portable"], attributes:{Capacity:"1TB"}, variants:[], avgRating:4.2, reviewCount:469, totalSold:88, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Mesh WiFi Router (2-pack)", shortDescription:"Whole-home coverage up to 350m2", description:"Eliminate dead zones with seamless mesh coverage across your whole home.", price:2299, compareAtPrice:2699, currency:"ZMW", images:["#f8fafc","#e2e8f0"], emoji:"📶", status:"active", stock:101, sku:"WIFI-M2", brand:"Vista", tags:["router","wifi","mesh"], attributes:{Coverage:"350 sqm"}, variants:[], avgRating:4.6, reviewCount:316, totalSold:369, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Action Camera 4K", shortDescription:"Waterproof to 10m, stabilized footage", description:"Capture every angle of your adventures in stabilized 4K.", price:2999, compareAtPrice:3499, currency:"ZMW", images:["#1a1a1a","#dc2626"], emoji:"📷", status:"active", stock:83, sku:"CAM-AC4", brand:"TechZone", tags:["camera","action","4k"], attributes:{Waterproof:"10m"}, variants:[{id:vid(),type:"style",value:"Standard",additionalPrice:0,stock:21,sku:"CAM-AC4-0"},{id:vid(),type:"style",value:"Adventure bundle",additionalPrice:450,stock:26,sku:"CAM-AC4-1"}], avgRating:4.3, reviewCount:394, totalSold:52, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Bluetooth Speaker", shortDescription:"360 degree sound, IPX7 waterproof, 20h battery", description:"Room-filling sound in a rugged, take-anywhere body.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#0f766e","#134e4a"], emoji:"🔊", status:"active", stock:51, sku:"SPK-360", brand:"AudioMax", tags:["speaker","bluetooth","waterproof"], attributes:{BatteryLife:"20h"}, variants:[{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:36,sku:"SPK-360-0"},{id:vid(),type:"color",value:"Teal",additionalPrice:0,stock:32,sku:"SPK-360-1"},{id:vid(),type:"color",value:"Red",additionalPrice:0,stock:28,sku:"SPK-360-2"}], avgRating:4.7, reviewCount:268, totalSold:319, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Power Bank 20000mAh", shortDescription:"Fast charging, dual USB-C output", description:"Two full smartphone charges in a slim, travel-friendly body.", price:599, compareAtPrice:749, currency:"ZMW", images:["#27272a","#52525b"], emoji:"🔋", status:"active", stock:83, sku:"PB-20K", brand:"TechZone", tags:["powerbank","charging"], attributes:{Capacity:"20000mAh"}, variants:[], avgRating:4.8, reviewCount:387, totalSold:144, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Tablet 11\" 128GB", shortDescription:"Quad speakers, all-day battery, stylus support", description:"A versatile tablet for streaming, sketching, and getting things done.", price:8999, compareAtPrice:10499, currency:"ZMW", images:["#e5e7eb","#d1d5db"], emoji:"📱", status:"active", stock:63, sku:"TAB-11", brand:"Galaxy", tags:["tablet","android"], attributes:{Storage:"128GB"}, variants:[{id:vid(),type:"style",value:"WiFi",additionalPrice:0,stock:25,sku:"TAB-11-0"},{id:vid(),type:"style",value:"WiFi + Cellular",additionalPrice:1200,stock:38,sku:"TAB-11-1"}], avgRating:4.5, reviewCount:341, totalSold:57, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Smart Home Hub", shortDescription:"Voice control, works with 100+ devices", description:"The central brain for lights, locks, and everything smart in your home.", price:1199, compareAtPrice:1399, currency:"ZMW", images:["#f1f5f9","#cbd5e1"], emoji:"🏠", status:"active", stock:91, sku:"HUB-SM", brand:"Vista", tags:["smart-home","hub"], attributes:{Compatibility:"100+ devices"}, variants:[], avgRating:4.3, reviewCount:280, totalSold:235, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Gaming Headset", shortDescription:"7.1 surround, noise-cancelling mic", description:"Hear every footstep with immersive surround sound and crystal-clear comms.", price:1099, compareAtPrice:1349, currency:"ZMW", images:["#18181b","#dc2626"], emoji:"🎮", status:"active", stock:83, sku:"GH-71", brand:"AudioMax", tags:["gaming","headset"], attributes:{Sound:"7.1 surround"}, variants:[], avgRating:4.6, reviewCount:478, totalSold:180, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Instant Photo Printer", shortDescription:"Prints from phone via Bluetooth", description:"Turn phone photos into pocket-sized prints in under a minute.", price:1499, compareAtPrice:1799, currency:"ZMW", images:["#fecdd3","#fda4af"], emoji:"🖨️", status:"active", stock:80, sku:"PR-IN", brand:"Vista", tags:["printer","photo"], attributes:{Connection:"Bluetooth"}, variants:[], avgRating:4.6, reviewCount:263, totalSold:55, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-01", sellerName:"TechZone", categoryId:"cat-01", categoryName:"Electronics", name:"Smart Doorbell Camera", shortDescription:"1080p HD, night vision, two-way audio", description:"See, hear, and speak to visitors from anywhere.", price:1799, compareAtPrice:2199, currency:"ZMW", images:["#18181b","#27272a"], emoji:"🔔", status:"active", stock:93, sku:"DB-CAM", brand:"Vista", tags:["security","camera","smart-home"], attributes:{Resolution:"1080p"}, variants:[], avgRating:4.7, reviewCount:63, totalSold:51, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Wrap Midi Dress", shortDescription:"Flattering wrap silhouette, lightweight jersey", description:"An easy, flattering wrap dress that moves from desk to dinner.", price:649, compareAtPrice:799, currency:"ZMW", images:["#7f1d1d","#991b1b"], emoji:"👗", status:"active", stock:41, sku:"DR-WRAP", brand:"Denimco", tags:["dress","women"], attributes:{Material:"Jersey"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:36,sku:"DR-WRAP-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:29,sku:"DR-WRAP-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:24,sku:"DR-WRAP-2"},{id:vid(),type:"size",value:"XL",additionalPrice:0,stock:37,sku:"DR-WRAP-3"}], avgRating:4.5, reviewCount:372, totalSold:197, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Bomber Jacket", shortDescription:"Water-resistant shell, ribbed cuffs", description:"A versatile bomber that layers well across every season.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#1f2937","#374151"], emoji:"🧥", status:"active", stock:70, sku:"JK-BOM", brand:"Stride", tags:["jacket","outerwear"], attributes:{Material:"Water-resistant"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:34,sku:"JK-BOM-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:18,sku:"JK-BOM-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:30,sku:"JK-BOM-2"}], avgRating:4.2, reviewCount:423, totalSold:167, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Leather Tote Bag", shortDescription:"Genuine leather, laptop compartment", description:"A structured everyday tote with room for a 15-inch laptop.", price:1299, compareAtPrice:1599, currency:"ZMW", images:["#78350f","#92400e"], emoji:"👜", status:"active", stock:75, sku:"BAG-TOTE", brand:"Skyline", tags:["bag","leather","women"], attributes:{Material:"Genuine leather"}, variants:[{id:vid(),type:"color",value:"Tan",additionalPrice:0,stock:30,sku:"BAG-TOTE-0"},{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:17,sku:"BAG-TOTE-1"}], avgRating:4.3, reviewCount:235, totalSold:301, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Leather Belt", shortDescription:"Full-grain leather, brushed buckle", description:"A classic belt that ages beautifully with wear.", price:349, compareAtPrice:null, currency:"ZMW", images:["#451a03","#78350f"], emoji:"👞", status:"active", stock:39, sku:"BLT-01", brand:"Denimco", tags:["belt","accessories"], attributes:{Material:"Full-grain leather"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:32,sku:"BLT-01-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:23,sku:"BLT-01-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:37,sku:"BLT-01-2"}], avgRating:4.5, reviewCount:213, totalSold:369, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Wool Blend Beanie", shortDescription:"Soft-touch knit, one size fits most", description:"A cosy knit beanie for the cooler months.", price:199, compareAtPrice:249, currency:"ZMW", images:["#1e3a8a","#1e40af"], emoji:"🧢", status:"active", stock:53, sku:"HAT-BN", brand:"Denimco", tags:["hat","winter"], attributes:{Material:"Wool blend"}, variants:[{id:vid(),type:"color",value:"Navy",additionalPrice:0,stock:17,sku:"HAT-BN-0"},{id:vid(),type:"color",value:"Charcoal",additionalPrice:0,stock:20,sku:"HAT-BN-1"},{id:vid(),type:"color",value:"Camel",additionalPrice:0,stock:19,sku:"HAT-BN-2"}], avgRating:4.4, reviewCount:149, totalSold:26, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Silk-Touch Scarf", shortDescription:"Lightweight, printed finish", description:"An elegant finishing touch for any outfit.", price:299, compareAtPrice:379, currency:"ZMW", images:["#be185d","#db2777"], emoji:"🧣", status:"active", stock:60, sku:"SCF-01", brand:"Skyline", tags:["scarf","accessories"], attributes:{Material:"Silk-touch"}, variants:[], avgRating:4.4, reviewCount:104, totalSold:234, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Cable Knit Sweater", shortDescription:"Chunky knit, crew neck", description:"A cosy staple sweater for layering through winter.", price:549, compareAtPrice:699, currency:"ZMW", images:["#78716c","#a8a29e"], emoji:"🧶", status:"active", stock:91, sku:"SWT-CBL", brand:"Denimco", tags:["sweater","winter"], attributes:{Material:"Cotton blend"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:19,sku:"SWT-CBL-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:37,sku:"SWT-CBL-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:31,sku:"SWT-CBL-2"},{id:vid(),type:"size",value:"XL",additionalPrice:0,stock:34,sku:"SWT-CBL-3"}], avgRating:4.7, reviewCount:408, totalSold:47, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Tailored Blazer", shortDescription:"Structured shoulders, single-button close", description:"A sharp blazer that elevates both casual and formal looks.", price:1199, compareAtPrice:1499, currency:"ZMW", images:["#111827","#1f2937"], emoji:"🧥", status:"active", stock:46, sku:"BLZ-01", brand:"Skyline", tags:["blazer","formal"], attributes:{Fit:"Tailored"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:27,sku:"BLZ-01-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:27,sku:"BLZ-01-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:27,sku:"BLZ-01-2"}], avgRating:4.5, reviewCount:276, totalSold:344, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Performance Leggings", shortDescription:"Squat-proof, moisture-wicking", description:"Studio-to-street leggings built to move with you.", price:449, compareAtPrice:549, currency:"ZMW", images:["#1e1b4b","#312e81"], emoji:"🩱", status:"active", stock:32, sku:"LEG-PF", brand:"Stride", tags:["activewear","leggings"], attributes:{Material:"Moisture-wicking"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:29,sku:"LEG-PF-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:20,sku:"LEG-PF-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:18,sku:"LEG-PF-2"}], avgRating:4.4, reviewCount:56, totalSold:72, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Leather Sandals", shortDescription:"Adjustable straps, cushioned footbed", description:"Comfortable leather sandals for warm-weather days.", price:399, compareAtPrice:499, currency:"ZMW", images:["#a16207","#ca8a04"], emoji:"👡", status:"active", stock:64, sku:"SND-01", brand:"Skyline", tags:["shoes","sandals"], attributes:{Material:"Leather"}, variants:[{id:vid(),type:"size",value:"6",additionalPrice:0,stock:26,sku:"SND-01-0"},{id:vid(),type:"size",value:"7",additionalPrice:0,stock:34,sku:"SND-01-1"},{id:vid(),type:"size",value:"8",additionalPrice:0,stock:15,sku:"SND-01-2"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:17,sku:"SND-01-3"}], avgRating:4.8, reviewCount:344, totalSold:212, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Chelsea Boots", shortDescription:"Genuine suede, elastic side panels", description:"Classic Chelsea boots that pair with everything.", price:1099, compareAtPrice:1349, currency:"ZMW", images:["#44403c","#57534e"], emoji:"🥾", status:"active", stock:38, sku:"BT-CHL", brand:"Skyline", tags:["shoes","boots"], attributes:{Material:"Suede"}, variants:[{id:vid(),type:"size",value:"7",additionalPrice:0,stock:34,sku:"BT-CHL-0"},{id:vid(),type:"size",value:"8",additionalPrice:0,stock:26,sku:"BT-CHL-1"},{id:vid(),type:"size",value:"9",additionalPrice:0,stock:30,sku:"BT-CHL-2"},{id:vid(),type:"size",value:"10",additionalPrice:0,stock:18,sku:"BT-CHL-3"}], avgRating:4.3, reviewCount:279, totalSold:258, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Minimalist Watch", shortDescription:"Leather strap, sapphire crystal", description:"A clean, understated watch for everyday wear.", price:1499, compareAtPrice:1799, currency:"ZMW", images:["#1c1917","#292524"], emoji:"⌚", status:"active", stock:22, sku:"WCH-MIN", brand:"Skyline", tags:["watch","accessories"], attributes:{Crystal:"Sapphire"}, variants:[{id:vid(),type:"style",value:"Brown leather",additionalPrice:0,stock:18,sku:"WCH-MIN-0"},{id:vid(),type:"style",value:"Black leather",additionalPrice:0,stock:38,sku:"WCH-MIN-1"}], avgRating:4.4, reviewCount:165, totalSold:265, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Polarized Aviators (Silver)", shortDescription:"Mirrored lenses, lightweight frame", description:"A cooler-toned take on the classic aviator.", price:649, compareAtPrice:829, currency:"ZMW", images:["#94a3b8","#64748b"], emoji:"🕶️", status:"active", stock:23, sku:"AV-SLV", brand:"Skyline", tags:["sunglasses","fashion"], attributes:{Lens:"Polarized"}, variants:[], avgRating:4.3, reviewCount:300, totalSold:205, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-02", sellerName:"Fashion Hub", categoryId:"cat-02", categoryName:"Fashion", name:"Linen Shirt", shortDescription:"Breathable weave, relaxed fit", description:"A breathable linen shirt built for warm days.", price:499, compareAtPrice:599, currency:"ZMW", images:["#f5f5f4","#e7e5e4"], emoji:"👔", status:"active", stock:65, sku:"SH-LIN", brand:"Denimco", tags:["shirt","men"], attributes:{Material:"Linen"}, variants:[{id:vid(),type:"size",value:"S",additionalPrice:0,stock:39,sku:"SH-LIN-0"},{id:vid(),type:"size",value:"M",additionalPrice:0,stock:31,sku:"SH-LIN-1"},{id:vid(),type:"size",value:"L",additionalPrice:0,stock:24,sku:"SH-LIN-2"},{id:vid(),type:"size",value:"XL",additionalPrice:0,stock:35,sku:"SH-LIN-3"}], avgRating:4.8, reviewCount:386, totalSold:153, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"3-Seater Sofa", shortDescription:"Solid wood frame, removable covers", description:"A comfortable centrepiece for any living room.", price:8999, compareAtPrice:10999, currency:"ZMW", images:["#78716c","#a8a29e"], emoji:"🛋️", status:"active", stock:44, sku:"SF-3S", brand:"Homeware", tags:["furniture","sofa"], attributes:{Frame:"Solid wood"}, variants:[{id:vid(),type:"color",value:"Charcoal",additionalPrice:0,stock:39,sku:"SF-3S-0"},{id:vid(),type:"color",value:"Sand",additionalPrice:0,stock:22,sku:"SF-3S-1"}], avgRating:4.6, reviewCount:428, totalSold:277, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Non-Stick Cookware Set (10pc)", shortDescription:"Induction-ready, PFOA-free coating", description:"Everything you need to outfit a kitchen from scratch.", price:1899, compareAtPrice:2299, currency:"ZMW", images:["#1c1c1e","#3f3f46"], emoji:"🍳", status:"active", stock:86, sku:"CK-10", brand:"Homeware", tags:["kitchen","cookware"], attributes:{Pieces:"10"}, variants:[], avgRating:4.8, reviewCount:448, totalSold:225, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Egyptian Cotton Bedding Set", shortDescription:"400 thread count, queen size", description:"Hotel-soft bedding for a genuinely restful night.", price:1099, compareAtPrice:1349, currency:"ZMW", images:["#f8fafc","#e2e8f0"], emoji:"🛏️", status:"active", stock:97, sku:"BD-EGY", brand:"Homeware", tags:["bedding","home"], attributes:{ThreadCount:"400"}, variants:[{id:vid(),type:"size",value:"Queen",additionalPrice:0,stock:30,sku:"BD-EGY-0"},{id:vid(),type:"size",value:"King",additionalPrice:250,stock:26,sku:"BD-EGY-1"}], avgRating:4.7, reviewCount:44, totalSold:163, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"LED Floor Lamp", shortDescription:"Dimmable, 3 color temperatures", description:"A modern floor lamp that adapts to any mood.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#292524","#44403c"], emoji:"💡", status:"active", stock:66, sku:"LMP-FL", brand:"Homeware", tags:["lighting","lamp"], attributes:{Dimmable:"Yes"}, variants:[], avgRating:4.9, reviewCount:258, totalSold:390, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Ceramic Dinnerware Set (16pc)", shortDescription:"Chip-resistant, dishwasher safe", description:"A complete dinnerware set for everyday and entertaining.", price:1299, compareAtPrice:1599, currency:"ZMW", images:["#fafaf9","#f5f5f4"], emoji:"🍽️", status:"active", stock:98, sku:"DW-16", brand:"Homeware", tags:["kitchen","dinnerware"], attributes:{Pieces:"16"}, variants:[{id:vid(),type:"color",value:"White",additionalPrice:0,stock:17,sku:"DW-16-0"},{id:vid(),type:"color",value:"Sage",additionalPrice:0,stock:22,sku:"DW-16-1"}], avgRating:4.3, reviewCount:270, totalSold:120, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Garden Tool Set (7pc)", shortDescription:"Rust-resistant steel, ergonomic grips", description:"A well-rounded toolkit for weekend gardeners.", price:549, compareAtPrice:699, currency:"ZMW", images:["#166534","#15803d"], emoji:"🌱", status:"active", stock:104, sku:"GT-7", brand:"Homeware", tags:["garden","tools"], attributes:{Pieces:"7"}, variants:[], avgRating:4.8, reviewCount:275, totalSold:354, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Storage Ottoman", shortDescription:"Woven texture, hidden storage", description:"A stylish spot to sit that also hides the clutter.", price:799, compareAtPrice:999, currency:"ZMW", images:["#a8a29e","#d6d3d1"], emoji:"🪑", status:"active", stock:101, sku:"OT-ST", brand:"Homeware", tags:["furniture","storage"], attributes:{Material:"Woven"}, variants:[{id:vid(),type:"color",value:"Natural",additionalPrice:0,stock:18,sku:"OT-ST-0"},{id:vid(),type:"color",value:"Charcoal",additionalPrice:0,stock:27,sku:"OT-ST-1"}], avgRating:4.7, reviewCount:414, totalSold:122, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Robot Vacuum", shortDescription:"App control, auto-empty base", description:"Hands-free cleaning that empties itself.", price:4499, compareAtPrice:5299, currency:"ZMW", images:["#18181b","#27272a"], emoji:"🤖", status:"active", stock:30, sku:"RV-01", brand:"CleanPro", tags:["vacuum","smart-home"], attributes:{Control:"App"}, variants:[], avgRating:4.4, reviewCount:440, totalSold:389, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Indoor Plant Bundle (3)", shortDescription:"Low-maintenance, air-purifying", description:"Three easy-care plants to bring a room to life.", price:449, compareAtPrice:null, currency:"ZMW", images:["#166534","#22c55e"], emoji:"🪴", status:"active", stock:79, sku:"PL-3", brand:"Homeware", tags:["plants","decor"], attributes:{Care:"Low-maintenance"}, variants:[], avgRating:4.7, reviewCount:117, totalSold:85, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Blackout Curtains (Pair)", shortDescription:"Thermal-insulated, noise-reducing", description:"Block light and noise for a better night's sleep.", price:649, compareAtPrice:799, currency:"ZMW", images:["#1e293b","#334155"], emoji:"🪟", status:"active", stock:90, sku:"CRT-BO", brand:"Homeware", tags:["curtains","home"], attributes:{Width:"140cm each"}, variants:[{id:vid(),type:"color",value:"Charcoal",additionalPrice:0,stock:40,sku:"CRT-BO-0"},{id:vid(),type:"color",value:"Navy",additionalPrice:0,stock:35,sku:"CRT-BO-1"},{id:vid(),type:"color",value:"Cream",additionalPrice:0,stock:19,sku:"CRT-BO-2"}], avgRating:4.6, reviewCount:335, totalSold:262, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Wall Art Print Set (3)", shortDescription:"Framed, ready to hang", description:"A curated set of framed prints for an instant gallery wall.", price:599, compareAtPrice:749, currency:"ZMW", images:["#e7e5e4","#d6d3d1"], emoji:"🖼️", status:"active", stock:33, sku:"ART-3", brand:"Homeware", tags:["decor","art"], attributes:{Pieces:"3"}, variants:[], avgRating:4.6, reviewCount:40, totalSold:27, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-03", sellerName:"HomeStyle", categoryId:"cat-03", categoryName:"Home & Garden", name:"Stand Fan 16-inch", shortDescription:"3-speed, oscillating, remote control", description:"Stay cool with powerful oscillating airflow.", price:699, compareAtPrice:849, currency:"ZMW", images:["#f5f5f4","#e7e5e4"], emoji:"🌀", status:"active", stock:47, sku:"FAN-16", brand:"Homeware", tags:["appliance","fan"], attributes:{Speeds:"3"}, variants:[], avgRating:4.6, reviewCount:101, totalSold:242, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Vitamin C Serum", shortDescription:"20% concentration, brightening", description:"A potent daily serum for brighter, more even-toned skin.", price:349, compareAtPrice:429, currency:"ZMW", images:["#fef3c7","#fde68a"], emoji:"🧴", status:"active", stock:61, sku:"SR-VC", brand:"PureGlow", tags:["skincare","serum"], attributes:{Concentration:"20%"}, variants:[], avgRating:4.2, reviewCount:138, totalSold:169, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Matte Liquid Lipstick Set (4)", shortDescription:"Long-wear, transfer-resistant", description:"Four wearable everyday shades in a long-lasting matte finish.", price:399, compareAtPrice:499, currency:"ZMW", images:["#be123c","#e11d48"], emoji:"💄", status:"active", stock:78, sku:"LP-4", brand:"PureGlow", tags:["makeup","lipstick"], attributes:{Pieces:"4"}, variants:[], avgRating:4.4, reviewCount:244, totalSold:87, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Hair Dryer 2200W", shortDescription:"Ionic technology, 3 heat settings", description:"Salon-quality drying that's kinder to your hair.", price:899, compareAtPrice:1099, currency:"ZMW", images:["#1c1c1e","#3f3f46"], emoji:"💇", status:"active", stock:84, sku:"HD-22", brand:"BrightSmile", tags:["hair","dryer"], attributes:{Wattage:"2200W"}, variants:[], avgRating:4.7, reviewCount:447, totalSold:284, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Facial Cleansing Brush", shortDescription:"Waterproof, 3 speed settings", description:"A deeper daily cleanse for smoother, clearer skin.", price:449, compareAtPrice:549, currency:"ZMW", images:["#fbcfe8","#f9a8d4"], emoji:"🧼", status:"active", stock:97, sku:"CB-01", brand:"PureGlow", tags:["skincare","tool"], attributes:{Waterproof:"Yes"}, variants:[{id:vid(),type:"color",value:"Pink",additionalPrice:0,stock:19,sku:"CB-01-0"},{id:vid(),type:"color",value:"White",additionalPrice:0,stock:32,sku:"CB-01-1"}], avgRating:4.3, reviewCount:291, totalSold:29, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Eau de Parfum 50ml", shortDescription:"Floral-woody, long-lasting", description:"A signature scent that lingers beautifully through the day.", price:649, compareAtPrice:799, currency:"ZMW", images:["#fce7f3","#fbcfe8"], emoji:"🌸", status:"active", stock:35, sku:"EDP-50", brand:"BeautyBar", tags:["fragrance","perfume"], attributes:{Volume:"50ml"}, variants:[], avgRating:4.2, reviewCount:439, totalSold:96, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Hair Straightener", shortDescription:"Ceramic plates, 230C max heat", description:"Sleek, salon-smooth results in minutes.", price:699, compareAtPrice:849, currency:"ZMW", images:["#18181b","#27272a"], emoji:"💁", status:"active", stock:33, sku:"STR-01", brand:"BrightSmile", tags:["hair","straightener"], attributes:{MaxHeat:"230C"}, variants:[], avgRating:4.6, reviewCount:196, totalSold:369, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Multivitamin Gummies (60ct)", shortDescription:"Daily essential vitamins, fruit flavors", description:"A tasty way to cover your daily vitamin bases.", price:249, compareAtPrice:299, currency:"ZMW", images:["#fed7aa","#fdba74"], emoji:"💊", status:"active", stock:32, sku:"VIT-60", brand:"PureGlow", tags:["wellness","supplements"], attributes:{Count:"60"}, variants:[], avgRating:4.8, reviewCount:59, totalSold:147, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Electric Shaver", shortDescription:"Wet & dry use, 60-min runtime", description:"A close, comfortable shave whether wet or dry.", price:799, compareAtPrice:949, currency:"ZMW", images:["#27272a","#3f3f46"], emoji:"🪒", status:"active", stock:76, sku:"SHV-01", brand:"BrightSmile", tags:["grooming","shaver"], attributes:{Runtime:"60 min"}, variants:[], avgRating:4.6, reviewCount:317, totalSold:34, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Hyaluronic Acid Moisturizer", shortDescription:"24h hydration, all skin types", description:"Deep, lasting hydration for every skin type.", price:299, compareAtPrice:369, currency:"ZMW", images:["#dbeafe","#bfdbfe"], emoji:"🧴", status:"active", stock:77, sku:"MST-HA", brand:"PureGlow", tags:["skincare","moisturizer"], attributes:{Hydration:"24h"}, variants:[], avgRating:4.4, reviewCount:288, totalSold:330, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Nail Care Kit (12pc)", shortDescription:"Stainless steel, travel case included", description:"A complete manicure and pedicure kit in a travel case.", price:349, compareAtPrice:null, currency:"ZMW", images:["#f3e8ff","#e9d5ff"], emoji:"💅", status:"active", stock:86, sku:"NL-12", brand:"BeautyBar", tags:["beauty","nails"], attributes:{Pieces:"12"}, variants:[], avgRating:4.6, reviewCount:443, totalSold:264, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Sunscreen SPF50", shortDescription:"Lightweight, no white cast", description:"Everyday sun protection that disappears on skin.", price:249, compareAtPrice:299, currency:"ZMW", images:["#fef9c3","#fef08a"], emoji:"☀️", status:"active", stock:77, sku:"SPF-50", brand:"PureGlow", tags:["skincare","sunscreen"], attributes:{SPF:"50"}, variants:[], avgRating:4.8, reviewCount:162, totalSold:306, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-05", sellerName:"BeautyBar", categoryId:"cat-04", categoryName:"Health & Beauty", name:"Aromatherapy Diffuser", shortDescription:"Ultrasonic, 7 LED colors", description:"Fill any room with scent and soft ambient light.", price:549, compareAtPrice:699, currency:"ZMW", images:["#f0fdfa","#ccfbf1"], emoji:"🕯️", status:"active", stock:50, sku:"DFF-01", brand:"BeautyBar", tags:["wellness","home"], attributes:{LEDColors:"7"}, variants:[], avgRating:4.3, reviewCount:92, totalSold:220, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Yoga Mat Pro", shortDescription:"6mm thick, non-slip texture, carry strap", description:"A cushioned, grippy mat for every kind of practice.", price:449, compareAtPrice:549, currency:"ZMW", images:["#7c3aed","#8b5cf6"], emoji:"🧘", status:"active", stock:102, sku:"YM-PRO", brand:"TrailTrack", tags:["yoga","fitness"], attributes:{Thickness:"6mm"}, variants:[{id:vid(),type:"color",value:"Purple",additionalPrice:0,stock:28,sku:"YM-PRO-0"},{id:vid(),type:"color",value:"Teal",additionalPrice:0,stock:17,sku:"YM-PRO-1"},{id:vid(),type:"color",value:"Charcoal",additionalPrice:0,stock:21,sku:"YM-PRO-2"}], avgRating:4.7, reviewCount:431, totalSold:82, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Adjustable Dumbbells (Pair)", shortDescription:"5-25kg per dumbbell, quick-lock", description:"Fifteen weight sets in one compact pair of dumbbells.", price:2499, compareAtPrice:2999, currency:"ZMW", images:["#18181b","#27272a"], emoji:"🏋️", status:"active", stock:48, sku:"DB-ADJ", brand:"TrailTrack", tags:["fitness","weights"], attributes:{Range:"5-25kg"}, variants:[], avgRating:4.7, reviewCount:103, totalSold:149, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Football (Match Size 5)", shortDescription:"FIFA-quality build, all-weather", description:"A durable match ball built for any surface.", price:349, compareAtPrice:429, currency:"ZMW", images:["#fafaf9","#e7e5e4"], emoji:"⚽", status:"active", stock:105, sku:"FB-M5", brand:"TrailTrack", tags:["football","sport"], attributes:{Size:"5"}, variants:[], avgRating:4.7, reviewCount:78, totalSold:223, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Cycling Helmet", shortDescription:"Adjustable fit, 18 vents", description:"Lightweight, well-ventilated protection for every ride.", price:699, compareAtPrice:849, currency:"ZMW", images:["#1e293b","#334155"], emoji:"🚴", status:"active", stock:60, sku:"HLM-CY", brand:"Stride", tags:["cycling","helmet"], attributes:{Vents:"18"}, variants:[{id:vid(),type:"size",value:"S/M",additionalPrice:0,stock:22,sku:"HLM-CY-0"},{id:vid(),type:"size",value:"L/XL",additionalPrice:0,stock:20,sku:"HLM-CY-1"}], avgRating:4.7, reviewCount:293, totalSold:226, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Resistance Bands Set (5)", shortDescription:"Varying resistance levels, door anchor", description:"A full home-gym-in-a-bag resistance set.", price:299, compareAtPrice:379, currency:"ZMW", images:["#dc2626","#ef4444"], emoji:"💪", status:"active", stock:22, sku:"RB-5", brand:"TrailTrack", tags:["fitness","bands"], attributes:{Pieces:"5"}, variants:[], avgRating:4.3, reviewCount:217, totalSold:29, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Insulated Water Bottle 1L", shortDescription:"Keeps cold 24h, hot 12h", description:"Stay hydrated through the longest training days.", price:249, compareAtPrice:299, currency:"ZMW", images:["#0891b2","#06b6d4"], emoji:"🧴", status:"active", stock:49, sku:"WB-1L", brand:"TrailTrack", tags:["hydration","accessories"], attributes:{Capacity:"1L"}, variants:[{id:vid(),type:"color",value:"Steel",additionalPrice:0,stock:27,sku:"WB-1L-0"},{id:vid(),type:"color",value:"Black",additionalPrice:0,stock:25,sku:"WB-1L-1"},{id:vid(),type:"color",value:"Blue",additionalPrice:0,stock:31,sku:"WB-1L-2"}], avgRating:4.6, reviewCount:292, totalSold:52, isFeatured:true, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Tennis Racket", shortDescription:"Graphite frame, pre-strung", description:"A balanced, control-oriented racket for club players.", price:1199, compareAtPrice:1449, currency:"ZMW", images:["#1e3a8a","#1e40af"], emoji:"🎾", status:"active", stock:43, sku:"TR-GR", brand:"TrailTrack", tags:["tennis","racket"], attributes:{Frame:"Graphite"}, variants:[], avgRating:4.9, reviewCount:83, totalSold:63, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Camping Tent (4-person)", shortDescription:"Waterproof, 10-min setup", description:"A spacious, quick-pitch tent for weekend getaways.", price:1799, compareAtPrice:2199, currency:"ZMW", images:["#166534","#15803d"], emoji:"⛺", status:"active", stock:53, sku:"TNT-4", brand:"TrailTrack", tags:["camping","outdoor"], attributes:{Capacity:"4 person"}, variants:[], avgRating:4.4, reviewCount:96, totalSold:236, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Boxing Gloves 12oz", shortDescription:"Synthetic leather, wrist support", description:"Durable sparring gloves with solid wrist support.", price:549, compareAtPrice:699, currency:"ZMW", images:["#dc2626","#991b1b"], emoji:"🥊", status:"active", stock:31, sku:"BG-12", brand:"TrailTrack", tags:["boxing","fitness"], attributes:{Weight:"12oz"}, variants:[], avgRating:4.5, reviewCount:304, totalSold:283, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-04", sellerName:"SportsPro", categoryId:"cat-05", categoryName:"Sports", name:"Swim Goggles", shortDescription:"Anti-fog, UV protection", description:"Clear, fog-free vision for laps and open water.", price:199, compareAtPrice:249, currency:"ZMW", images:["#0e7490","#0891b2"], emoji:"🏊", status:"active", stock:54, sku:"SG-01", brand:"TrailTrack", tags:["swimming","goggles"], attributes:{AntiFog:"Yes"}, variants:[], avgRating:4.4, reviewCount:439, totalSold:372, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"The Psychology of Money", shortDescription:"Timeless lessons on wealth and happiness", description:"A short, sharp read on how people actually think about money.", price:179, compareAtPrice:219, currency:"ZMW", images:["#065f46","#047857"], emoji:"📗", status:"active", stock:53, sku:"BK-POM", brand:"BookWorld Press", tags:["finance","bestseller"], attributes:{Format:"Paperback"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:15,sku:"BK-POM-0"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:70,stock:35,sku:"BK-POM-1"}], avgRating:4.3, reviewCount:163, totalSold:62, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"A5 Hardcover Notebook (3-pack)", shortDescription:"Dotted pages, ribbon bookmark", description:"A set of premium notebooks for journaling or planning.", price:249, compareAtPrice:299, currency:"ZMW", images:["#1c1917","#292524"], emoji:"📓", status:"active", stock:54, sku:"NB-A5-3", brand:"BookWorld", tags:["stationery","notebook"], attributes:{Pieces:"3"}, variants:[], avgRating:4.8, reviewCount:262, totalSold:25, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"The Midnight Library", shortDescription:"A novel about the lives we could have lived", description:"A moving, widely loved novel about choices and regret.", price:159, compareAtPrice:199, currency:"ZMW", images:["#1e1b4b","#312e81"], emoji:"📘", status:"active", stock:53, sku:"BK-ML", brand:"BookWorld Press", tags:["fiction","bestseller"], attributes:{Format:"Paperback"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:34,sku:"BK-ML-0"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:65,stock:19,sku:"BK-ML-1"}], avgRating:4.2, reviewCount:393, totalSold:142, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Fountain Pen Set", shortDescription:"Includes ink cartridges and converter", description:"A smooth-writing fountain pen for everyday elegance.", price:399, compareAtPrice:499, currency:"ZMW", images:["#7f1d1d","#991b1b"], emoji:"🖋️", status:"active", stock:46, sku:"PEN-FT", brand:"BookWorld", tags:["stationery","pen"], attributes:{Includes:"Ink + converter"}, variants:[], avgRating:4.2, reviewCount:133, totalSold:179, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Sapiens: A Brief History of Humankind", shortDescription:"A sweeping look at how we got here", description:"One of the most talked-about nonfiction books of the decade.", price:219, compareAtPrice:269, currency:"ZMW", images:["#78350f","#92400e"], emoji:"📙", status:"active", stock:52, sku:"BK-SAP", brand:"BookWorld Press", tags:["nonfiction","history"], attributes:{Format:"Paperback"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:24,sku:"BK-SAP-0"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:80,stock:29,sku:"BK-SAP-1"}], avgRating:4.6, reviewCount:121, totalSold:158, isFeatured:false, isFlashDeal:true, flashDealEndsAt:future(1) },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Kids' Picture Book Bundle (5)", shortDescription:"Ages 3-7, colourful illustrations", description:"Five beloved picture books bundled for early readers.", price:349, compareAtPrice:429, currency:"ZMW", images:["#f59e0b","#fbbf24"], emoji:"📚", status:"active", stock:85, sku:"BK-KIDS5", brand:"BookWorld Press", tags:["children","bundle"], attributes:{Pieces:"5"}, variants:[], avgRating:4.2, reviewCount:39, totalSold:395, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Desk Organizer Set", shortDescription:"Bamboo, 6 compartments", description:"A tidy, natural-material home for desk essentials.", price:299, compareAtPrice:369, currency:"ZMW", images:["#a16207","#ca8a04"], emoji:"🗂️", status:"active", stock:104, sku:"ORG-DSK", brand:"BookWorld", tags:["stationery","organizer"], attributes:{Material:"Bamboo"}, variants:[], avgRating:4.5, reviewCount:258, totalSold:74, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"1984 by George Orwell", shortDescription:"A dystopian classic", description:"The classic that shaped a century of thinking about power and truth.", price:149, compareAtPrice:179, currency:"ZMW", images:["#18181b","#27272a"], emoji:"📕", status:"active", stock:49, sku:"BK-1984", brand:"BookWorld Press", tags:["fiction","classic"], attributes:{Format:"Paperback"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:30,sku:"BK-1984-0"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:60,stock:32,sku:"BK-1984-1"}], avgRating:4.8, reviewCount:231, totalSold:279, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"Highlighter Set (6 colors)", shortDescription:"Chisel tip, low-bleed ink", description:"Vivid, low-bleed highlighters for study or planning.", price:99, compareAtPrice:null, currency:"ZMW", images:["#facc15","#fde047"], emoji:"🖍️", status:"active", stock:64, sku:"HL-6", brand:"BookWorld", tags:["stationery","highlighters"], attributes:{Pieces:"6"}, variants:[], avgRating:4.4, reviewCount:456, totalSold:381, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
  { sellerId:"sel-06", sellerName:"BookWorld", categoryId:"cat-06", categoryName:"Books & Media", name:"The 5AM Club", shortDescription:"A guide to owning your morning", description:"A popular framework for building a high-performance morning routine.", price:189, compareAtPrice:229, currency:"ZMW", images:["#0c4a6e","#075985"], emoji:"📔", status:"active", stock:27, sku:"BK-5AM", brand:"BookWorld Press", tags:["self-help"], attributes:{Format:"Paperback"}, variants:[{id:vid(),type:"style",value:"Paperback",additionalPrice:0,stock:16,sku:"BK-5AM-0"},{id:vid(),type:"style",value:"Hardcover",additionalPrice:65,stock:19,sku:"BK-5AM-1"}], avgRating:4.2, reviewCount:350, totalSold:399, isFeatured:false, isFlashDeal:false, flashDealEndsAt:null },
];

export const PRODUCTS: Product[] = SEED.map((p) => ({
  ...p,
  id: randomUUID(),
  slug: p.name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  createdAt: ago(rand(720, 43800)),
  updatedAt: ago(rand(0, 720)),
}));

CATEGORIES.forEach(c => { c.productCount = PRODUCTS.filter(p => p.categoryId === c.id).length; });

// ─── Coupons ────────────────────────────────────────────────────────────────
export const COUPONS: Coupon[] = [
  { id:"cpn-01", code:"WELCOME10", type:"percentage",    value:10, minOrderAmount:200, maxDiscountAmount:100, usageLimit:null, usageCount:0, validFrom:ago(43800), validTo:future(365), active:true, sellerId:null },
  { id:"cpn-02", code:"SAVE50",    type:"fixed_amount",  value:50, minOrderAmount:400, maxDiscountAmount:null, usageLimit:5000, usageCount:0, validFrom:ago(4380), validTo:future(30), active:true, sellerId:null },
  { id:"cpn-03", code:"FREESHIP",  type:"free_shipping", value:0,  minOrderAmount:100, maxDiscountAmount:null, usageLimit:null, usageCount:0, validFrom:ago(8760), validTo:future(90), active:true, sellerId:null },
];
