/**
 * Files a product under a storefront category by what the product IS.
 *
 * CJ's category pages are loosely curated (car diagnostic scanners under
 * "Office", pet toys under "Toys", blankets under "School"), so the page a
 * product was found on is weak evidence. The product's own name is strong
 * evidence. These rules read a NAME; the first match wins, so "who it's
 * for" rules (pets, toys, babies, cars) sit above "what it is" rules -- a dog
 * bowl is a pet product before it's kitchenware, a baby blanket is baby gear
 * before it's bedding. The supplier category path is used only when the
 * name says nothing recognisable (see cjCategoryMap.ts for those rules).
 */
import { broadCategoryFor, matchCjCategory, resolveCategory } from "./cjCategoryMap";

/** Bump when the rules below change: stored products are re-filed once per version. */
export const CATEGORY_RULES_VERSION = 1;

const NAME_RULES: [fine: string, re: RegExp][] = [
  // ── Who it's for ──────────────────────────────────────────────────────────
  ["cat-csv-pets", /\b(?:pets?|dogs?|doggy|pupp(?:y|ies)|cats?|kittens?|kitty|guinea pigs?|hamsters?|rabbits?|ferrets?|parrots?|aquarium|fish tank|bird ?cage|litter box|cat litter|leash)\b(?! ?eye)/i],
  ["cat-csv-toys", /\b(?:rc|remote control|toy|model) (?:cars?|trucks?|drones?|planes?|boats?|tanks?|excavators?)\b|\btoys?\b|plush (?:toys?|dolls?|animals?|pillows? toy)|\bplushies?\b|\bdolls?\b|\bpuzzles?\b|building blocks?|\blego\b|stuffed animal|fidget|\bslime\b|board games?|\bjigsaw\b|kids'? (?:game|kitchen|tent)/i],
  ["cat-csv-baby", /\b(?:baby|babies|infants?|newborns?|toddlers?|maternity|pregnan\w*|nursing|breast ?pump|strollers?|pacifiers?|teethers?|rompers?|onesies?|bibs?|feeding bottles?|diapers?|napp(?:y|ies)|cribs?|cradles?)\b|\b(?:children'?s|childrens|kids'?|girls'?|boys'?)\b[^,]*\b(?:dress|jumpsuit|clothes|clothing|outfit|set|skirt|pants|shirt|top|pajamas?|hoodie|jacket|coat|shoes|sandals|sneakers|boots)\b/i],
  ["cat-csv-automotive", /\bdash ?cams?\b|\bcars?\b|\bvehicles?\b|in-vehicle|\bmotorcycles?\b|\bmotorbikes?\b|\bobd ?(?:ii|2)?\b|carplay|android auto|\btrucks?\b|\btyres?\b|\btires?\b|windshield|wipers?|steering wheel|rear ?view|\bfor auto\b|\bauto (?:parts?|accessor\w*)|armrest|interior modification|engine fault|diagnostic (?:tool|scanner)|\be-?bikes?\b|\bscooters?\b/i],

  // ── Specific electronics ─────────────────────────────────────────────────
  ["cat-01", /\bsmart ?(?:watch(?:es)?|bands?|bracelets?|rings?|glasses)\b|fitness trackers?|translat(?:or|ion)|walkie[- ]?talkies?|intercom|\bradios?\b|e-?readers?/i],
  ["cat-csv-computer-acc", /\b(?:tablet|ipad|macbook|laptop|notebook computer|kindle)\b[^,]*\b(?:case|cover|sleeve|shell|bag|stand|holder|bracket|keyboard|film|protector|skin|display|screen|lcd)\b|\bssd\b|solid[- ]state|hard (?:drives?|disks?)|\bhdd\b|keyboards?|\bmouse\b|\bmice\b|mouse ?pads?|usb hubs?|\bhub\b|docking station|webcams?|\bmonitors?\b(?! (?:baby|blood))|printers?|ink cartridges?|toner|memory cards?|\bsd cards?\b|flash drives?|usb (?:drives?|sticks?)|card readers?|laptop (?:stand|cooler|cooling)|cooling (?:pad|base|bracket)|graphics cards?|motherboard|cpu cooler|privacy (?:films?|screens?|filters?)/i],
  ["cat-csv-mobile-acc", /\bphones? (?:cases?|covers?|holders?|stands?|mounts?|straps?|lens(?:es)?|grips?|rings?|bags?|pouch|shells?|films?|charms?|chains?|lanyards?|display|screen|lcd)\b|\b(?:mobile|cell) phone (?:cases?|covers?|holders?|stands?|accessor\w*|lcd|display|screen|charging)|\biphone\b|\bsamsung\b|\bhuawei\b|\bxiaomi\b|screen protectors?|tempered glass|power ?banks?|\bchargers?\b|charging (?:cables?|heads?|docks?|stations?|stands?|pads?)|wireless charg\w*|data cables?|usb[- ]?c cables?|lightning cables?|selfie sticks?|protective case|hydrogel|tempered (?:glass|film)|protective film|anti-?peep\w*|ceramic (?:film|coating)|lens (?:films?|protectors?)|soft film|screen film|touch assembly|digitizer|lcd assembly|replacement screen|oled lcd|lazy (?:phone )?holder|\bcase\b(?=.*\b(?:drop|anti-?fall\w*|anti-?fingerprint|shockproof))/i],
  ["cat-csv-audio", /ear ?phones?|head ?phones?|ear ?buds?|headsets?|speakers?|sound ?bars?|microphones?|\bmics?\b|\bmp[34]\b|amplifiers?|\bhi-?fi\b|karaoke|turntables?|audio (?:adapters?|cables?|converters?)|\baux\b|cd players?|record players?|music players?|\bdrums?\b|ukulele|guitars?|pianos?|keyboard instrument|violins?|kalimba|harmonica|musical instruments?|percussion|\bflutes?\b/i],
  ["cat-csv-gaming", /game ?pads?|game (?:controllers?|handles?|consoles?|joysticks?|rockers?)|\bgaming\b|joysticks?|\bconsoles?\b|arcade|\bps[345]\b|\bxbox\b|nintendo|\bswitch (?:case|controllers?|joy)|\bwii\b|\bngc\b|\bvr\b|handheld game|retro game/i],
  ["cat-csv-networking", /routers?|\bwi-?fi[l]? (?:adapters?|extenders?|repeaters?|boosters?|dongles?|cards?)|network (?:cards?|adapters?|interface|switch|cables?)|ethernet|\bmodems?\b|\blan\b|signal (?:boosters?|amplifiers?)|access points?|\bpoe\b|bluetooth (?:receivers?|adapters?|dongles?|transmitters?)|\bdongles?\b|range extenders?|wireless usb adapter/i],
  ["cat-csv-smart-home", /security cameras?|surveillance|\bcctv\b|\bip cam\w*|door ?bells?|smart (?:plugs?|sockets?|switch(?:es)?|bulbs?|locks?|home|curtains?|sensors?)|wi-?fi (?:sockets?|plugs?|switch(?:es)?)|touch (?:wall )?switch|\balarms?\b|anti-?lost|gps trackers?|\btrackers?\b|baby monitor|door (?:sensors?|locks?)|fingerprint lock|smoke detectors?|access control/i],
  ["cat-csv-cameras", /\bcameras?\b|camcorders?|\btripods?\b|\bdrones?\b|gimbals?|camera lens|telecentric|machine vision|zoom lens|\blens(?:es)?\b|ring lights?|photography|photo studio|\bstudio\b|fill lights?|softbox|microscopes?|telescopes?|binoculars?|night vision|trail cam|action cam/i],
  ["cat-csv-tv", /\btv (?:box|stick|mount|bracket|antenna|remote|bars?)|\btvs?\b|television|projectors?|\bhdmi\b|streaming (?:device|stick)|media players?|set[- ]top box|remote control(?:ler)?s?\b|screen mirroring|wireless (?:screen|display)|hologra\w*/i],
  ["cat-csv-smartphones", /\bsmart ?phones?\b|\bmini phone\b|\b(?:mobile|cell) ?phones?\b|\bandroid phone\b|landline|telephone/i],
  ["cat-csv-garden", /\bgarden|\blawns?\b|\bpatio|\byard\b|planters?|flower ?pots?|watering|sprinklers?|\bhoses?\b|greenhouse|sun ?shade net|shade net|\bseeds?\b|\bbbq\b|barbecue|\bgrills?\b|pruning|\bshears\b|plant (?:supports?|stands?|climbing)|climbing (?:frame|vine)|bird feeders?|pool (?:floats?|cleaners?)|\bponds?\b/i],
  ["cat-csv-solar", /\bsolar\b/i],

  // ── Personal care ───────────────────────────────────────────────────────
  ["cat-csv-health", /massag\w*|\bposture\b|\bbraces?\b|orthop(?:a)?edic|orthotic|thermometers?|blood (?:pressure|glucose|oxygen)|oximeters?|glucose|\becg\b|capsules?|softgels?|supplements?|probiotics?|vitamins?|gumm(?:y|ies)|shilajit|pain relief|hearing aids?|\bdental\b|tooth ?brush(?:es)?|teeth whitening|oral (?:care|irrigator)|water flossers?|first aid|medical|acupressure|heating pads?|\bcupping\b|prostate|grounding|therapy|\bgua sha\b|joint gloves|compression (?:sleeves?|socks)|chok(?:ing|e) (?:rescue|emergency|device)|anti[- ]choking|airway|nebuli[sz]ers?|inhalers?/i],
  ["cat-csv-beauty", /\bnails?\b|manicure|pedicure|lip(?:stick|s? gloss| balm| liner| oil)|make ?-?up|cosmetics?|foundation|concealer|eye ?shadows?|eye ?liners?|mascara|eyelash(?:es)?|\blashes\b|eyebrows?|\bblush\b|\bserums?\b|moisturi[sz]\w*|\bcreams?\b|lotions?|cleansers?|sunscreen|skin ?care|face (?:masks?|wash|rollers?|cleaners?|brush(?:es)?|steamers?)|facial|(?:eye|sheet|sleeping|firming|mud|clay) (?:masks?|patch(?:es)?)|eye patch(?:es)?|microneedle|depilat\w*|hair ?remov\w*|wax strips?|epilators?|shav(?:ers?|ing)|razors?|trimmers?|hair (?:dryers?|straighteners?|curlers?|clips?|ties?|bands?|pins?|brush(?:es)?|combs?|oil|masks?|extensions?)|\bwigs?\b|\bcombs?\b|perfumes?|fragrances?|cologne|deodorant|antiperspirant|tattoo|beauty|body (?:wash|scrub|lotion|oil)|bath bombs?|\bsoaps?\b|makeup brush(?:es)?|cosmetic bags?|curling (?:irons?|wands?)|straighteners?/i],

  // ── Home ────────────────────────────────────────────────────────────────
  ["cat-csv-kitchen", /kitchen|cookware|frying pans?|\bpans?\b|\bwoks?\b|saucepans?|casserole|stock ?pots?|hot ?pots?|\bstew\b|rice cookers?|pressure cookers?|slow cookers?|air fryers?|\bovens?\b|microwaves?|toasters?|kettles?|blenders?|juicers?|\bmixers?\b|food processors?|coffee|espresso|tea ?pots?|\bknives\b|\bknife\b|cutting boards?|chopping boards?|peelers?|graters?|spatulas?|ladles?|\bwhisks?\b|\btongs\b|utensils?|tableware|dinnerware|cutlery|chopsticks?|\bplates?\b|\bbowls?\b|\bcups?\b|\bmugs?\b|tumblers?|water bottles?|thermos|vacuum (?:flasks?|sealers?)|food (?:sealers?|storage|containers?)|lunch ?box(?:es)?|bento|baking|bakeware|cake (?:molds?|moulds?|pans?)|ice (?:cube|cream)|dish ?(?:cloths?|racks?|washers?)|drying racks?|\bspices?\b|seasoning|bottle openers?|\bwine\b|cocktail|\bstoves?\b|porridge|egg (?:cookers?|beaters?)|dumplings?|noodles?/i],
  ["cat-csv-cleaning", /cleaners?\b|cleaning|\bmops?\b|brooms?|dust ?pans?|dusters?|\bscrub\w*|sponges?|\bwipes?\b|trash (?:cans?|bags?|bins?)|garbage|rubbish|waste bins?|laundry|detergent|\bstains?\b|lint (?:rollers?|removers?)|\bhangers?\b|clothes (?:racks?|drying)|storage (?:box(?:es)?|bags?|baskets?|bins?|racks?|organi[sz]ers?)|organi[sz]ers?|dust covers?|shoe racks?|\bhooks?\b(?!-on)|vacuum (?:storage|compression) bags?|\bdrains?\b|toilet (?:brush(?:es)?|cleaners?)|mite/i],
  ["cat-csv-home-appliances", /\bfans?\b|humidif\w*|dehumidifiers?|air purifiers?|air condition\w*|\bheaters?\b|electric blankets?|water (?:filters?|purifiers?|dispensers?)|filter cartridges?|vacuum cleaners?|robot vacuums?|\bvacuum\b(?! (?:storage|compression|bags?))|steam (?:irons?|mops?)|garment steamers?|(?<!soldering )\biron\b(?! tip)(?!.*(?:cutting|metal|alumin))|sewing machines?|washing machines?|dishwashers?|refrigerators?|\bfridges?\b|freezers?|aroma diffusers?|\bdiffusers?\b|atomiz\w*|rocking chair cradle/i],
  ["cat-csv-travel", /suitcases?|luggage|carry-?on|trolley (?:cases?|bags?)|\btravel (?:bags?|pillows?|adapters?|organi[sz]ers?|kits?|bottles?|pouch(?:es)?|wallets?)|passport|packing cubes?|toiletry bags?|neck pillows?/i],
  ["cat-csv-bags", /\bbags?\b|backpacks?|rucksacks?|wallets?|purses?|handbags?|\btotes?\b|clutch(?:es)?|crossbody|shoulder bags?|fanny packs?|waist bags?|card holders?|coin purses?|briefcases?|satchels?|\bpouch(?:es)?\b|key ?chains?|key (?:cases?|holders?|rings?|bags?)/i],
  ["cat-csv-shoes", /\bshoes?\b|sneakers?|trainers|\bboots?\b|booties|sandals?|slippers?|\bheels?\b|high[- ]heeled|stilettos?|\bflats\b|loafers?|flip[- ]?flops?|\bmules?\b|\bclogs?\b|espadrilles?|insoles?|shoe ?laces?|footwear|\bslides\b/i],
  ["cat-csv-jewellery", /\bwatch(?:es)?\b|necklaces?|pendants?|earrings?|ear (?:studs?|cuffs?|clips?)|\bstuds?\b|bracelets?|bangles?|anklets?|\brings?\b(?! lights?)|brooch(?:es)?|jewel(?:le)?ry|\bcharms?\b|chokers?|cufflinks|tiaras?|body chains?/i],
  ["cat-csv-sports", /\byoga\b|pilates|fitness|\bgym\b|workout|exercise|dumbbells?|kettlebells?|resistance bands?|jump(?:ing)? ropes?|skipping ropes?|push[- ]?ups?|sit[- ]?ups?|ab (?:rollers?|wheels?)|treadmills?|\bcamping\b|\btents?\b|sleeping bags?|hiking|trekking|climbing|fishing|\blures?\b|golf|tennis|badminton|ping pong|basketball|football|soccer|volleyball|baseball|rugby|cricket|hockey|boxing|martial|swim(?:ming)?|goggles|snorkel\w*|diving|\bsurf\w*|skateboards?|\bskates?\b|skiing|\bski\b|snowboards?|cycling|bicycles?|\bbikes?\b|helmets?|running|marathon|\bsports?\b|lanterns?|headlamps?|flashlights?|\btorch(?:es)?\b|compass|hunting|archery/i],
  ["cat-csv-school", /diamond painting|cross-?stitch|embroidery kits?|paint by numbers|pipe cleaners?/i],
  ["cat-csv-diy", /\bdrills?\b|screwdrivers?|wrench(?:es)?|spanners?|pliers|hammers?|\bsaws?\b|chisels?|hex keys?|allen keys?|socket sets?|tool (?:sets?|kits?|box(?:es)?|bags?)|\btools?\b|tape measures?|measuring tapes?|spirit levels?|laser levels?|multimeters?|soldering|welding|glue guns?|\bglue\b|sealant|\bpaint\b|paint(?:ing)? (?:brush(?:es)?|rollers?)|sandpaper|grinders?|polishers?|cutting machines?|\bclamps?\b|\bscrews?\b|\bbolts?\b|filter (?:mesh|cloth)|\btape\b|work lights?/i],
  ["cat-csv-electrical", /\bsockets?\b|extension (?:cords?|leads?|sockets?)|power strips?|\bplugs?\b|\bswitch(?:es)?\b|\bwires?\b|\bwiring\b|circuit breakers?|\bfuses?\b|faucets?|shower ?heads?|plumbing|\bpipes?\b|\bvalves?\b|\bbasins?\b|toilet seats?/i],
  ["cat-csv-batteries", /\bbatter(?:y|ies)\b(?! display)|power stations?|\b18650\b|aa batter|jump starter|\binverters?\b|\bups\b/i],
  ["cat-csv-safety", /lock cylinders?|pad ?locks?|door (?:locks?|stoppers?)|(?:bike|cable|combination|puck|shackle|cabinet|drawer|safe) locks?|safety|reflective|hi-?vis|fire (?:extinguishers?|blankets?|alarms?)|smoke alarms?|emergency|anti-?theft|safe box|work gloves|ear ?plugs?|respirators?|dust masks?|hard hats?|knee pads?/i],
  ["cat-csv-decor", /bedding|bed ?sheets?|\bsheets?\b|duvets?|quilt(?:s|ed)?\b|comforters?|bedspreads?|coverlets?|pillow ?cases?|\bshams\b|pillows?|cushions?|\bthrows?\b|blankets?|curtains?|\brugs?\b|carpets?|door ?mats?|towels?|bath (?:mats?|robes?)|table ?cloths?|vases?|candles?|\blamps?\b|lamp ?shades?|chandeliers?|\blights?\b|lighting|led strips?|string lights|fairy lights|night lights?|\bneon\b|wall (?:art|stickers?|decals?|decor|hangings?|clocks?)|\bclocks?\b|photo frames?|picture frames?|mirrors?|artificial (?:flowers?|plants?|leaves)|fake (?:flowers?|plants?)|bouquets?|wreaths?|garlands?|christmas|xmas|halloween|easter|ornaments?|figurines?|statues?|sculptures?|\bdecor\b|\bdecorations?\b|incense|tapestry|posters?|music box(?:es)?/i],
  ["cat-csv-furniture", /furniture|\bchairs?\b|\btables?\b|\bsofas?\b|couch(?:es)?|shel(?:f|ves)|bookcases?|cabinets?|\bdesks?\b|bed frames?|\bbeds?\b|mattress(?:es)?|wardrobes?|dressers?|nightstands?|\bstools?\b|benches?|ottomans?|bean ?bags?|coat (?:racks?|stands?)|tv stands?|hammocks?/i],
  ["cat-csv-office", /\bpens?\b|pencils?|\bmarkers?\b|highlighters?|notebooks?|notepads?|sticky notes|stationery|staplers?|\bstaples\b|paper ?clips?|binders?|folders?|envelopes?|\blabels?\b|label (?:makers?|printers?)|calculators?|desk (?:organi[sz]ers?|lamps?|mats?|pads?)|whiteboards?|\bscanners?\b|barcode|scan (?:code )?guns?|receipt printers?|\bpos\b|shredders?|laminators?|\bstamps?\b|self-inking|\boffice\b/i],
  ["cat-csv-school", /\bschool\b|\bstudents?\b|pencil cases?|crayons?|colou?r(?:ed|ing) pencils?|watercolou?rs?|paint (?:sets?|brushes)|sketch\w*|drawing|art supplies|\bcrafts?\b|crochet (?:kits?|hooks?|yarn)|knitting|\byarn\b|embroidery|sewing (?:kits?|thread)|\bbeads?\b|ribbons?|scrapbook\w*|stickers?|educational|flash ?cards|\bglobes?\b/i],
  ["cat-csv-fashion", /dress(?:es)?\b|shirts?|\bt-?shirts?\b|\btees?\b|blouses?|\btops?\b|camisoles?|\bvests?\b|hoodies?|sweat ?shirts?|sweaters?|jumpers?|cardigans?|pullovers?|jackets?|\bcoats?\b|blazers?|parkas?|outerwear|\bpants\b|trousers|jeans|leggings|joggers|\bshorts\b|skirts?|jumpsuits?|overalls|\bsuits?\b|lingerie|underwear|\bbras?\b|panties|briefs|boxers|\bsocks?\b|stockings|tights|pajamas?|pyjamas?|sleepwear|nightgowns?|\brobes?\b|swimsuits?|swimwear|bikinis?|beachwear|cover-?ups?|\bhats?\b|\bcaps?\b|beanies?|berets?|scarf|scarves|shawls?|gloves?|mittens|\bbelts?\b|sunglasses|eyeglasses|glasses frames?|\bties\b|bow ties?|suspenders|costumes?|cosplay|uniforms?|aprons?|clothing|clothes|outfits?|knitwear|fleece|shapewear|corsets?|kimonos?|hijabs?|gowns?|\bveils?\b|bridal|wedding dress(?:es)?|leg warmers|arm warmers|waist cinchers?/i],
  ["cat-csv-grocery", /\bfood\b(?! (?:containers?|storage|sealers?|processors?|dispensers?|bowls?))|snacks?|\bcandy\b|candies|chocolates?|\btea\b(?! ?pots?)|coffee beans|\bsauces?\b|\bhoney\b|\bnuts\b|dried fruits?/i],

  // ── Generic electronics catch-all, last ─────────────────────────────────
  ["cat-01", /bluetooth|wireless|\busb\b|electronic|\bdigital\b|\bled\b|rechargeable|\bsmart\b|\bgps\b|\bwi-?fi\b|\bhd\b|\b4k\b|adapters?|converters?/i],
];

/** Our category for a product, from its NAME -- null when the name says nothing recognisable. */
export function classifyProductName(name: string | null | undefined): string | null {
  if (!name) return null;
  const hit = NAME_RULES.find(([, re]) => re.test(name));
  return hit ? hit[0] : null;
}

/**
 * Where a product belongs: from its name first, then the supplier category
 * path, then the fallback -- always a category that exists in this database.
 */
export function categorizeProduct(name: string, pathLevels: (string | null | undefined)[], known: Set<string>, fallback: string): string | null {
  const byName = classifyProductName(name);
  if (byName && known.has(byName)) return byName;
  if (byName && known.has(broadCategoryFor(byName))) return broadCategoryFor(byName);
  return resolveCategory(matchCjCategory(...pathLevels), known, fallback);
}
